### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by sjackman** [aquaskyline/LRSIM#13]
`simulateLinkedReads` failed with the error `Floating point exception`. I'm trying to simulate reads with no simulated variations. Perhaps that's related.
```
❯❯❯ simulateLinkedReads.pl -z 16 -x 524 -d 1 -1 0 -4 0 -7 0 -0 0 -r GRCh38.wrap.fa -p sim.lr
Sat Jan 20 14:19:27 2018: sim.lr.status
Sat Jan 20 14:19:27 2018: Variant simulation mode enabled
Sat Jan 20 14:19:27 2018: SURVIVOR start
Sat Jan 20 14:19:27 2018: Running: /gsc/btl/linuxbrew/Cellar/lrsim/1.0/SURVIVOR 0 GRCh38.wrap.fa sim.lr.hap.parameter 0 sim.lr.hap 0
sh: line 1: 21814 Floating point exception(core dumped) /gsc/btl/linuxbrew/Cellar/lrsim/1.0/SURVIVOR 0 GRCh38.wrap.fa sim.lr.hap.parameter 0 sim.lr.hap 0 > /dev/null
Sat Jan 20 14:21:21 2018: SURVIVOR error on missing sim.lr.hapA.fasta
No such file or directory at /gsc/btl/linuxbrew/Cellar/lrsim/1.0/simulateLinkedReads.pl line 738.
unable to delete sim.lr.hapA.fasta at exit
unable to delete sim.lr.hap.homAB.insertions.fa at exit
unable to delete sim.lr.hap.hetA.insertions.fa at exit
unable to delete sim.lr.hap.hetB.insertions.fa at exit
unable to delete sim.lr.hapB.fasta at exit
Command exited with non-zero status 2
❯❯❯ cat sim.lr.status
Sat Jan 20 14:19:27 2018: sim.lr.status
Sat Jan 20 14:19:27 2018: Variant simulation mode enabled
Sat Jan 20 14:19:27 2018: SURVIVOR start
Sat Jan 20 14:19:27 2018: Running: /gsc/btl/linuxbrew/Cellar/lrsim/1.0/SURVIVOR 0 GRCh38.wrap.fa sim.lr.hap.parameter 0 sim.lr.hap 0
Sat Jan 20 14:21:21 2018: SURVIVOR error on missing sim.lr.hapA.fasta
```

**Comment by sjackman** [comment]
Using `-g` rather than `-r` avoids running SURVIVOR and gets further:
```
simulateLinkedReads.pl -z 16 -x 524 -d 1 -1 0 -4 0 -7 0 -0 0 -g GRCh38.fa,GRCh38.fa -p sim.lr
```

**Comment by aquaskyline** [comment]
Using `-g` with only one copy of `GRCh38.fa` also work.

**Comment by sjackman** [comment]
Also relevant is this commit 8abd7c15ed7962d820f8ec79ec5412fff0511ff4
> added option n to disable all SVs

**Comment by sinamajidian** [comment]
Hi
I run this 
` ~/Install/LRSIM/simulateLinkedReads.pl  -r soltub_40.fasta   -p out 
`

The output is

> Fri Dec 21 12:57:18 2018: out.status
Fri Dec 21 12:57:18 2018: Variant simulation mode enabled
Fri Dec 21 12:57:18 2018: SURVIVOR start
Fri Dec 21 12:57:18 2018: Running: /home/majid001/Install/LRSIM/SURVIVOR 0 soltub_40.fasta out.hap.parameter 0 out.hap 1000
Floating point exception
Fri Dec 21 12:57:18 2018: SURVIVOR error on missing out.hapA.fasta
No such file or directory at /home/majid001/Install/LRSIM/simulateLinkedReads.pl line 748.
unable to delete out.hapA.fasta at exit
unable to delete out.hap.hetB.insertions.fa at exit
unable to delete out.hap.homAB.insertions.fa at exit
unable to delete out.hap.hetA.insertions.fa at exit
unable to delete out.hapB.fasta at exit

In my pipeline, firstly, I should generate two haplotypes from the reference genome, then, generate some reads. Any idea? 
I think using `-g` is not a good idea for my case. Because, haplotypes will not be created.
