### ISSUE TITLE
linked reads option setting

### ISSUE THREAD

**Issue by thelingxichen** [aquaskyline/LRSIM#7]
Hi aquaskyline,

I am trying to use LRSIM to simulate 50X linked reads for a small portion of human genome. My selected genomic region is around 1M bp. To adapt the small reference set, I intend to do following changes on linked reads options.
    -x = coverage * my_reference_length/(insertion_size + sd of pairs) = 50*1M/(350+35)
    -f = default setting
    -t = human_genome_length / my_reference_length * default_t = 3,000,000,000 /  1,000,000 * 1,500,000
    -m = default setting

To get the best simulated linked reads data, any suggestion on my modification? 

Thanks a lot.
Lindsay

**Comment by aquaskyline** [comment]
Hi Lindsay,

It depends on what scenario are you simulating. Say if you want to study how available linked-read technologies such as 10x would perform on human genome by using a 1Mbp small chunk, you can scale down the default -t by 3,000 times, while other parameters remain the same. If you are targeting a modified or totally different lined-read technology, you can set the parameters to the exact values of the technology. In your description, you increased -t by 3,000 times, this seems to be impossible in the real life. For -x coverage, it means the read coverage instead of the physical coverage, which means that you don't need to put it the insert size and standard deviation.
